services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/templates
    depends_on:
      - app
    networks:
      manabloxnet:
        aliases:
          - api.manablox.test

  app:
    image: node:20
    hostname: app
    working_dir: /app
    volumes:
      - .:/app
    networks:
      - manabloxnet
    command: sh -c "yarn && yarn build && exec yarn dev"
    # command: sh -c "yarn && yarn build && exec yarn preview --host=0.0.0.0"

networks:
  manabloxnet:
    driver: bridge
    