services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/templates
    depends_on:
      - api
    networks:
      manabloxnet:
        aliases:
          - api.manablox.test

  db:
    image: mongodb/mongodb-community-server:latest
    ports:
      - 27017:27017
    networks:
      - manabloxnet

  api:
    image: node:20
    hostname: api
    working_dir: /app
    volumes:
      - .:/app
    networks:
      - manabloxnet
    command: sh -c "yarn && exec yarn build & exec yarn dev"
    # command: sh -c "yarn && yarn build && exec yarn preview --host=0.0.0.0"

networks:
  manabloxnet:
    driver: bridge
    